### ISSUE TITLE
Contextual Awareness

### ISSUE THREAD

**Issue by ArivAfonso** [swapnilg915/FAQ_Bot_using_BERT#1]
Hey!! I know this may seem a bit out of place but I am building a virtual assistant and wanted to add the ability to understand the context of my words (like follow-up questions) For eg:-
Me: Who painted Mona Lisa
Assistant: Leonardo de Vinci
Me: When was he born?
Assistant: 1475

PS: I know this may seem out of place but this is the closest and most recently updated repo I found

**Comment by swapnilg915** [comment]
Hi Ariv,

Thanks for a question.
For your use case you can try RASA : It has this ability. Also let me know
whether it was useful for you or not.
https://rasa.com/docs/rasa/contextual-conversations/

**Comment by ArivAfonso** [comment]
Rasa is built more for chatbots rather than than fully functional assistants. I am researching dialogflow and may find something so pls keep this issue open. 
https://cloud.google.com/dialogflow/es/docs/contexts-overview#:~:text=Dialogflow%20contexts%20are%20similar%20to,to%20correctly%20match%20an%20intent.

**Comment by ArivAfonso** [comment]
I found something called Symbl's Language Insights API on Google Cloud's Marketplace which fits my requirements. Thanks for the help.
